### PR TITLE
Migrate to new backend registrations

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] Requires https://github.com/nextcloud/server/pull/31007
- [x] https://github.com/nextcloud/calendar_resource_management/pull/74

### CODE REVIEW

**Review by tcitworld — APPROVED** [review]

**Comment by tcitworld** [comment]
Do we and should we do backports on this app?

**Comment by tcitworld** [comment]
Lint issues + CI must be updated

**Comment by ChristophWurst** [comment]
> Do we and should we do backports on this app (not applicable in this case of course)?

For fixes I would say so

**Review by miaulalala — APPROVED** [review]

**Comment by ChristophWurst** [comment]
We can only do this if info.xml says 24+

**Comment by st3iny** [comment]
> > We can only do this if info.xml says 24+
> 
> So? What's missing? NC24 is there! The older "release" is available for older NC versions. Should you also publish it on apps.nextcloud.com?

Older releases are still supported (as per info.xml). Please refer to https://github.com/nextcloud/calendar_resource_management/issues/14 for the release.

**Comment by ChristophWurst** [comment]
23 will reach EOL soon, ref https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule. Then we can require 24 for this app and ship the enhancement.

**Comment by ChristophWurst** [comment]
We can merge this after https://github.com/nextcloud/calendar_resource_management/pull/74

**Comment by miaulalala** [comment]
#74 is in

**Review by st3iny — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Bildschirmfoto vom 2023-01-16 14-37-13

:shipit:

**Pull request merged**
