### PR TITLE
[stable0.1] Run workflow on NC stable23

### PR DESCRIPTION
**Pull request by miaulalala**

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Open the PR against stable0.1, master of this repo should still test master of server

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Drop all the unrelated commits

* git rebase -i origin/stable0.1
* remove unwanted commits
* git rebase --contine

**Review by st3iny — APPROVED** [review]
LGTM and workflow runs :shipit:

**Pull request merged**
